config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#welcome'

  get 'static_pages/welcome'
  get 'static_pages/about'
  get 'static_pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails 7 Alpha with importmap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render 'shared/header' %>
    <main class="container flex-grow mx-auto mt-20 px-5">
      <%= yield %>
    </main>

<%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
    <footer class="footer bg-gray-100 bottom-0">
      <div class="px-4 pt-16 w-full container  bottom-0 max-w-screen-xl mx-auto">
        <div class="grid gap-16 row-gap-10 mb-8 lg:grid-cols-6">
          <div class="md:max-w-md lg:col-span-2">
            <a href="/" aria-label="Go home" title="Company" class="inline-flex items-center">
              <%= image_tag 'rocket.svg', alt: 'Welcome ALPHA', class:"object-cover h-6 rounded shadow-lg lg:rounded-none lg:shadow-none" %>
              <span class="ml-2 text-xl font-extrabold tracking-wide text-gray-800 uppercase">ALPHA 7</span>
            </a>
            <div class="mt-4 lg:max-w-sm">
              <p class="text-sm text-gray-800">
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.
              </p>
              <p class="mt-4 text-sm text-gray-800">
                Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
              </p>
            </div>
          </div>
          <div class="grid grid-cols-2 gap-5 row-gap-8 lg:col-span-4 md:grid-cols-4">
            <div>
              <p class="font-semibold tracking-wide text-gray-800">Category</p>
              <ul class="mt-2 space-y-2">
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">News</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">World</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Games</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">References</a>
                </li>
              </ul>
            </div>
            <div>
              <p class="font-semibold tracking-wide text-gray-800">Business</p>
              <ul class="mt-2 space-y-2">
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Web</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">eCommerce</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Business</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Entertainment</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Portfolio</a>
                </li>
              </ul>
            </div>
            <div>
              <p class="font-semibold tracking-wide text-gray-800">Apples</p>
              <ul class="mt-2 space-y-2">
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Media</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Brochure</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Nonprofit</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Educational</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Projects</a>
                </li>
              </ul>
            </div>
            <div>
              <p class="font-semibold tracking-wide text-gray-800">Cherry</p>
              <ul class="mt-2 space-y-2">
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Infopreneur</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Personal</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Wiki</a>
                </li>
                <li>
                  <a href="/" class="text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400">Forum</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="flex flex-col justify-between pt-5 pb-10 border-t sm:flex-row">
          <p class="text-sm text-gray-600">
            © Copyright 2020 Lorem Inc. All rights reserved.
          </p>
          <div class="flex items-center mt-4 space-x-4 sm:mt-0">
            <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
              <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
                <path
                  d="M24,4.6c-0.9,0.4-1.8,0.7-2.8,0.8c1-0.6,1.8-1.6,2.2-2.7c-1,0.6-2,1-3.1,1.2c-0.9-1-2.2-1.6-3.6-1.6 c-2.7,0-4.9,2.2-4.9,4.9c0,0.4,0,0.8,0.1,1.1C7.7,8.1,4.1,6.1,1.7,3.1C1.2,3.9,1,4.7,1,5.6c0,1.7,0.9,3.2,2.2,4.1 C2.4,9.7,1.6,9.5,1,9.1c0,0,0,0,0,0.1c0,2.4,1.7,4.4,3.9,4.8c-0.4,0.1-0.8,0.2-1.3,0.2c-0.3,0-0.6,0-0.9-0.1c0.6,2,2.4,3.4,4.6,3.4 c-1.7,1.3-3.8,2.1-6.1,2.1c-0.4,0-0.8,0-1.2-0.1c2.2,1.4,4.8,2.2,7.5,2.2c9.1,0,14-7.5,14-14c0-0.2,0-0.4,0-0.6 C22.5,6.4,23.3,5.5,24,4.6z"
                ></path>
              </svg>
            </a>
            <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
              <svg viewBox="0 0 30 30" fill="currentColor" class="h-6">
                <circle cx="15" cy="15" r="4"></circle>
                <path
                  d="M19.999,3h-10C6.14,3,3,6.141,3,10.001v10C3,23.86,6.141,27,10.001,27h10C23.86,27,27,23.859,27,19.999v-10   C27,6.14,23.859,3,19.999,3z M15,21c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S18.309,21,15,21z M22,9c-0.552,0-1-0.448-1-1   c0-0.552,0.448-1,1-1s1,0.448,1,1C23,8.552,22.552,9,22,9z"
                ></path>
              </svg>
            </a>
            <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
              <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
                <path
                  d="M22,0H2C0.895,0,0,0.895,0,2v20c0,1.105,0.895,2,2,2h11v-9h-3v-4h3V8.413c0-3.1,1.893-4.788,4.659-4.788 c1.325,0,2.463,0.099,2.795,0.143v3.24l-1.918,0.001c-1.504,0-1.795,0.715-1.795,1.763V11h4.44l-1,4h-3.44v9H22c1.105,0,2-0.895,2-2 V2C24,0.895,23.105,0,22,0z"
                ></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    <footer>

app/views/shared/_header.html.erb
<header class="header bg-white">
      <nav class="shadow ">
          <div class="max-w-7xl mx-auto px-8">
              <div class="flex items-center justify-between h-16">
                  <div class="w-full justify-between flex items-center">
                      <a class="flex-shrink-0" href="/">
                      <%= image_tag 'rocket.svg', alt: 'Welcome ALPHA', class:"object-cover h-10 rounded shadow-lg lg:rounded-none lg:shadow-none" %>
                      </a>
                      <div class="hidden md:block">
                          <div class="ml-10 flex items-baseline space-x-4">
                              <a class="text-gray-700 hover:text-gray-300 block px-3 py-2 text-base font-medium" href="/#">
                                  Home
                              </a>
                              <a class="text-gray-700 hover:text-gray-300 block px-3 py-2 text-base font-medium" href="/#">
                                  About
                              </a>
                              <a class="text-gray-700 hover:text-gray-300 block px-3 py-2 text-base font-medium" href="/#">
                                  Contact
                              </a>

                              <div class="inline-block text-sm px-4 py-2 leading-none rounded no-underline text-gray hover:text-gray-900 hover:bg-white mt-4 lg:mt-0">
                                <div class="relative" data-controller="dropdown">
                                  <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="inline-block select-none">
                                    <span class="appearance-none flex items-center inline-block text-gray-700">
                                      <% if static_pages_welcome_path %>
                                        <%#= image_tag avatar_url_for(current_user), class: "rounded-full h-8 w-8 align-middle" %>
                                        <p class="text-gray-700 hover:text-gray-300 text-base font-medium">Welcome</p>
                                      <% end %>
                                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="h-4 w-4"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path></svg>
                                    </span>
                                  </div>
                                  <div data-dropdown-target="menu" class="absolute right-0 mt-2 hidden z-10">
                                    <div class="bg-white shadow rounded border overflow-hidden">
                                        <%= link_to 'Items',  root_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block pl-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
                                        <%= link_to 'Welcome', root_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
                                        <%= link_to 'Accounts', root_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
                                        <%= link_to 'Billing',  root_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
                                        <%= link_to 'Sign Out', root_path, method: :delete, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
                                    </div>
                                  </div>
                                </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="block">
                      <div class="ml-4 flex items-center md:ml-6">
                      </div>
                  </div>
                  <div class="-mr-2 flex md:hidden">
                      <button class="text-gray-800 hover:text-gray-300 inline-flex items-center justify-center p-2 rounded-md focus:outline-none">
                          <svg width="20" height="20" fill="currentColor" class="h-8 w-8" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                              <path d="M1664 1344v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45zm0-512v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45zm0-512v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45z">
                              </path>
                          </svg>
                      </button>
                  </div>
              </div>
          </div>
      </nav>
    </header>

app/views/static_pages/contact.html.erb
<div>
  <h1 class="text-xl font-bold">StaticPages#contact</h1>
  <p>Find me in app/views/static_pages/contact.html.erb</p>
<div>

app/views/static_pages/welcome.html.erb
<div class="relative px-4 pt-16 lg:py-32 md:px-8 0 w-full mb-8">
  <div class="max-w-xl mx-auto lg:max-w-screen-xl">
    <div class="mb-16 lg:max-w-lg lg:mb-0">
      <div class="max-w-xl mb-6">
        <div>
          <p class="inline-block px-3 py-px mb-4 text-xs font-semibold tracking-wider text-teal-900 uppercase rounded-full bg-green-300">
            Brand new
          </p>
        </div>
        <h2 class="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
          The quick, brown fox<br class="hidden md:block" />
          jumps over
          <span class="inline-block text-purple-400">a lazy dog</span>
        </h2>
        <p class="text-base text-gray-700 md:text-lg">
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. explicabo.
        </p>
      </div>
      <div class="flex items-center">
        <a
          href="/"
          class="inline-flex items-center justify-center h-12 px-6 mr-6 font-medium tracking-wide text-white transition duration-200 rounded shadow-md bg-purple-400 hover:bg-purple-700 focus:shadow-outline focus:outline-none"
        >
          Get started
        </a>
        <a href="/" aria-label="" class="inline-flex items-center font-semibold transition-colors duration-200 text-purple-400 hover:text-purple">Learn more</a>
      </div>
    </div>
  </div>
  <div class="flex justify-center h-full overflow-hidden lg:w-2/3 xl:w-1/2 lg:absolute lg:justify-start lg:bottom-0 lg:right-0 lg:items-end">
    <img src="https://kitwind.io/assets/kometa/full-browser.png" class="object-cover object-top w-full h-64 max-w-xl -mb-16 rounded shadow-2xl lg:ml-64 xl:ml-8 lg:-mb-24 xl:-mb-28 lg:h-auto lg:max-w-screen-md" alt="" />
  </div>
</div>



<div class="container mx-auto px-6 p-6 bg-white dark:bg-gray-800 mb-8">
    <div class="mb-16 text-center">
        <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">
            Features
        </h2>
        <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
            A better way to live
        </p>
    </div>
    <div class="flex flex-wrap my-12 dark:text-white">
        <div class="w-full border-b md:w-1/2 md:border-r lg:w-1/3 p-8">
            <div class="flex items-center mb-6">
                <svg width="20" height="20" fill="currentColor" class="h-6 w-6 text-indigo-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                    <path d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z">
                    </path>
                </svg>
                <div class="ml-4 text-xl">
                    Increase sales
                </div>
            </div>
            <p class="leading-loose text-gray-500 dark:text-gray-200 text-md">
                Receive more sales by selling across multple sales channels instead of just having a single point of entry.
            </p>
        </div>
        <div class="w-full border-b md:w-1/2 lg:w-1/3 lg:border-r p-8">
            <div class="flex items-center mb-6">
                <svg width="20" height="20" fill="currentColor" class="h-6 w-6 text-indigo-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                    <path d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z">
                    </path>
                </svg>
                <div class="ml-4 text-xl">
                    Overlays
                </div>
            </div>
            <p class="leading-loose text-gray-500 dark:text-gray-200 text-md">
                Apply beautiful overlays to every product image distributed through our platform. A visual touch.
            </p>
        </div>
        <div class="w-full border-b md:w-1/2 md:border-r lg:w-1/3 lg:border-r-0 p-8">
            <div class="flex items-center mb-6">
                <svg width="20" height="20" fill="currentColor" class="h-6 w-6 text-indigo-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                    <path d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z">
                    </path>
                </svg>
                <div class="ml-4 text-xl">
                    Control
                </div>
            </div>
            <p class="leading-loose text-gray-500 dark:text-gray-200 text-md">
                Apply filters and control which products to sell on each sales channel. E.g. exclude products with low margins.
            </p>
        </div>
        <div class="w-full border-b md:w-1/2 lg:w-1/3 lg:border-r lg:border-b-0 p-8">
            <div class="flex items-center mb-6">
                <svg width="20" height="20" fill="currentColor" class="h-6 w-6 text-indigo-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                    <path d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z">
                    </path>
                </svg>
                <div class="ml-4 text-xl">
                    Mapping
                </div>
            </div>
            <p class="leading-loose text-gray-500 dark:text-gray-200 text-md">
                Map product categories with each sales channels&#x27; own categories and achieve better results and lower costs.
            </p>
        </div>
        <div class="w-full border-b md:w-1/2 md:border-r md:border-b-0 lg:w-1/3 lg:border-b-0 p-8">
            <div class="flex items-center mb-6">
                <svg width="20" height="20" fill="currentColor" class="h-6 w-6 text-indigo-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                    <path d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z">
                    </path>
                </svg>
                <div class="ml-4 text-xl">
                    Fill the missing
                </div>
            </div>
            <p class="leading-loose text-gray-500 dark:text-gray-200 text-md">
                Modify products with extra properties and achieve the maximum output for each installed sales channel.
            </p>
        </div>
        <div class="w-full md:w-1/2 lg:w-1/3 p-8">
            <div class="flex items-center mb-6">
                <svg width="20" height="20" fill="currentColor" class="h-6 w-6 text-indigo-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                    <path d="M491 1536l91-91-235-235-91 91v107h128v128h107zm523-928q0-22-22-22-10 0-17 7l-542 542q-7 7-7 17 0 22 22 22 10 0 17-7l542-542q7-7 7-17zm-54-192l416 416-832 832h-416v-416zm683 96q0 53-37 90l-166 166-416-416 166-165q36-38 90-38 53 0 91 38l235 234q37 39 37 91z">
                    </path>
                </svg>
                <div class="ml-4 text-xl">
                    Dynamic Texts
                </div>
            </div>
            <p class="leading-loose text-gray-500 dark:text-gray-200 text-md">
                Build unique product titles and descriptions instead of spending days manually editing each product.
            </p>
        </div>
    </div>
</div>